myproject/blog/urls.py
from django.urls import path, reverse_lazy
from . import views
from . import models

from django.views.generic import DeleteView


urlpatterns = [
    path('', views.home_view, name='home'),
    path('trips/', views.TripsListView.as_view(), name='trips'),

    path('liked-trips/', views.liked_trips_view, name='liked_trips'),
    path('like/<int:trip_id>/', views.like_trip, name='like_trip'),
    path('unlike/<int:trip_id>/', views.unlike_trip_view, name='unlike_trip'),

    path('login/', views.user_login_view, name='login'),
    path('logout/', views.user_logout_view, name='logout'),
    path('signup/', views.user_signup_view, name='signup'),

    path('trip/<int:pk>/', views.trip_detail_view, name='trip'),
    path('add-trip/', views.TripCreateView.as_view(), name='add_trip'),
    path('update-trip/<int:pk>/', views.TripUpdateView.as_view(), name='edit_trip'),
    path('delete-trip/<int:pk>/', DeleteView.as_view(model=models.Trip, success_url=reverse_lazy('trips')), name='delete_trip'),

    path('expense/create/<int:trip_id>/', views.expense_create, name='expense_create'),
    path('expense/update/<int:trip_id>/<int:expense_id>/', views.expense_update, name='expense_update'),
    path('expense/delete/<int:trip_id>/<int:expense_id>/', views.expense_delete, name='expense_delete'),

    path('todo/create/<int:trip_id>/', views.todo_create, name='todo_create'),
    path('todo/update/<int:trip_id>/<int:todo_id>/', views.todo_update, name='todo_update'),
    path('todo/delete/<int:trip_id>/<int:todo_id>/', views.todo_delete, name='todo_delete'),
]

myproject/blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nazwa")
    alpha_2 = models.SlugField(max_length=2, unique=True, verbose_name="Kod alpha 2")

    class Meta:
        verbose_name = "Kraj"
        verbose_name_plural = "Kraje"
        ordering = ['name']

    def __str__(self):
        return self.name

class Expense(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nazwa")
    planned_cost = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Planowany koszt")
    actual_cost = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Rzeczywisty koszt")

    class Meta:
        verbose_name = "Wydatek"
        verbose_name_plural = "Wydatki"

    def __str__(self):
        return self.name

class ToDo(models.Model):
    task = models.CharField(max_length=100, verbose_name="Zadanie")
    status = models.CharField(max_length=1, choices=( ('z', 'Zrobione'), ('n', 'Nie zrobione') ), default='n', verbose_name="Status")

    class Meta:
        verbose_name = "Do zrobienia"
        verbose_name_plural = "Do zrobienia"

    def __str__(self):
        return self.task

class User(AbstractUser):
    email = models.EmailField(unique=True, verbose_name="Email")

    class Meta:
        verbose_name = "Użytkownik"
        verbose_name_plural = "Użytkownicy"

    def __str__(self):
        return self.username
class SouvenirOffer(models.Model):
    title = models.CharField(max_length=100, verbose_name="Tytuł")
    description = models.TextField( verbose_name="Opis")
    publication_date = models.DateField(verbose_name="Data publikacji", help_text="Data w formacie YYYY-MM-DD")
    availability = models.BooleanField(verbose_name="Dostępność", default=True)
    offered_or_wanted = models.CharField(max_length=1, choices=( ('o', 'Oferowane'), ('p', 'Poszukiwane') ), default='o')
    author = models.ForeignKey('blog.User', on_delete=models.PROTECT, verbose_name="Autor")
    origin_country = models.ForeignKey('blog.Country', on_delete=models.PROTECT, verbose_name="Kraj pochodzenia")

    class Meta:
        verbose_name = "Oferta pamiątki"
        verbose_name_plural = "Oferty pamiątek"

    def __str__(self):
        return self.title

class Like(models.Model):
    user = models.ForeignKey('blog.User', on_delete=models.PROTECT, verbose_name="Użytkownik")
    trip = models.ForeignKey('blog.Trip', on_delete=models.PROTECT, verbose_name="Wycieczka")

    class Meta:
        verbose_name = "Polubienie"
        verbose_name_plural = "Polubienia"

    def __str__(self):
        return f"{self.user} lubi {self.trip}"

class Trip(models.Model):
    title = models.CharField(max_length=100, verbose_name="Tytuł")
    start_date = models.DateField(verbose_name="Data startu", help_text="Data w formacie YYYY-MM-DD")
    end_date = models.DateField(verbose_name="Data końca", help_text="Data w formacie YYYY-MM-DD")
    description = models.TextField( verbose_name="Opis")
    author = models.ForeignKey('blog.User', on_delete=models.PROTECT, verbose_name="Autor")
    countries = models.ManyToManyField('blog.Country', verbose_name="Kraje")
    expenses = models.ManyToManyField('blog.Expense', verbose_name="Wydatki", related_name='trips', blank=True)
    to_dos = models.ManyToManyField('blog.ToDo', verbose_name="Do zrobienia", related_name='trips', blank=True)

    class Meta:
        verbose_name = "Wycieczka"
        verbose_name_plural = "Wycieczki"

    def __str__(self):
        return self.description

class TravelProposal(models.Model):
    title = models.CharField(max_length=100, verbose_name="Tytuł")
    description = models.TextField( verbose_name="Opis")
    publication_date = models.DateField(verbose_name="Data publikacji", help_text="Data w formacie YYYY-MM-DD")
    availability = models.BooleanField(verbose_name="Dostępność", default=True)
    countries = models.ManyToManyField('blog.Country', verbose_name="Kraje")
    author = models.ForeignKey('blog.User', on_delete=models.PROTECT, null=True, verbose_name="Autor")

    class Meta:
        verbose_name = "Propozycja podróży"
        verbose_name_plural = "Propozycje podróży"

    def __str__(self):
        return self.title

myproject/blog/forms.py
from .models import Trip, Country, Expense, ToDo
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Wymagane. Podaj prawidłowy adres email.')
    username = forms.CharField(label='Nazwa użytkownika', max_length=150, help_text='Wymagane. Maksymalnie 150 znaków. Litery, cyfry i @/./+/-/_ tylko.')
    password1 = forms.CharField(label='Hasło', widget=forms.PasswordInput, help_text='Wymagane. Hasło musi zawierać co najmniej 8 znaków.')
    password2 = forms.CharField(label='Potwierdź hasło', widget=forms.PasswordInput, help_text='Wprowadź to samo hasło, dla potwierdzenia.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class TripForm(forms.ModelForm):
    countries = forms.ModelMultipleChoiceField(
        queryset=Country.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label="Kraje"
    )
    class Meta:
        model = Trip
        fields = ['title', 'start_date', 'end_date', 'description', 'countries']


class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['name', 'planned_cost', 'actual_cost']


class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ['task', 'status']

myproject/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Aplikacja Django{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'blog/styles/style.css' %}" type="text/css">
    {% block extra_head %}
    {% endblock %}
</head>
<body>

<header>
    {% include 'blog/menu.html' %}
</header>

<main>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</main>

<footer>
    <p>Jakub Sury - projekt końcowy SDA</p>
</footer>

</body>
</html>

myproject/blog/templates/blog/expense_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>Potwierdź usunięcie wydatku</h1>
    <br>
    <p>Czy na pewno chcesz usunąć ten wydatek?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Tak, usuń</button>
    </form>
{% endblock %}

myproject/blog/templates/blog/expense_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>Dodaj/Edytuj Wydatek</h1>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit">Zapisz</button>
    </form>
{% endblock %}

myproject/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Wycieczki innych</h1>
        <br>

        {% for trip in other_trips %}
            <div>
                <p><a href="{% url 'trip' trip.id %}"><strong>{{ trip.title }}</strong></a></p>
                <p>Od {{ trip.end_date|date:"d.m.Y" }} do {{ trip.end_date|date:"d.m.Y" }}</p>
                <p>Autor: {{ trip.author }}</p>
                <form action="{% url 'like_trip' trip.id %}" method="post">
                    {% csrf_token %}
                    {% if trip.user_has_liked %}
                        <button type="submit">Odlub</button>
                    {% else %}
                        <button type="submit">Polub</button>
                    {% endif %}
                </form>
            </div>
            <br>
        {% endfor %}
    {% else %}
        <h1>Zarejestruj się lub zaloguj!</h1>
    {% endif %}
{% endblock %}

myproject/blog/templates/blog/liked_trips.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title %}Favourites{% endblock %}
{% block page_title %} Polubione wycieczki {% endblock %}

{% block content %}
    <h1>Polubione wycieczki</h1>
    <br>
    {% for like in liked_trips %}
        <div>
            <p><a href="{% url 'trip' like.trip.id %}"><strong>{{ like.trip.title }}</strong></a></p>
            <p>Od {{ like.trip.end_date|date:"d.m.Y" }} do {{ like.trip.end_date|date:"d.m.Y" }}</p>
            <p>Autor: {{ like.trip.author }}</p>
            <form action="{% url 'unlike_trip' like.trip.id %}" method="POST">
                {% csrf_token %}
                <button type="submit">Odlub</button>
            </form>
        </div>
        <br>
    {% endfor %}
{% endblock %}

myproject/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <div class="login-container">
        <h1>Zaloguj się</h1>
        <br>
        {% if error_message %}
            <div class="alert alert-danger">{{ error_message }}</div>
        {% endif %}
        <form method="POST" class="login-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Nazwa użytkownika:</label>
                <input type="text" id="username" name="username">
            </div>
            <div class="form-group">
                <label for="password">Hasło:</label>
                <input type="password" id="password" name="password">
            </div>
            <button type="submit" class="btn btn-primary">Zaloguj się</button>
        </form>
    </div>
{% endblock %}

myproject/blog/templates/blog/menu.html
<nav class="navbar">
    <div class="container">
        <div>
            <a class="navbar-brand" href="{% url 'home' %}" class="logo">Portal podróżnika</a>
        </div>
        <ul class="nav-list">
            <li class="nav-item"><a href="{% url 'home' %}" class="nav-link">Strona główna</a></li>

            {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'trips' %}" class="nav-link">Moje wycieczki</a></li>
                <li class="nav-item"><a href="{% url 'liked_trips' %}" class="nav-link">Polubione</a></li>
                <li class="nav-item"><a href="{% url 'home' %}" class="nav-link">{{ user.get_username }}</a></li>
                <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Wyloguj</a></li>
            {% else %}
                <li class="nav-item"><a href="{% url 'signup' %}" class="nav-link">Rejestracja</a></li>
                <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Zaloguj</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

myproject/blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <div class="signup-container">
        <h1>Zarejestruj się</h1>
        <br>
        <form method="POST" class="signup-form">
            {% csrf_token %}
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username }}
                <small class="text-muted">Nazwa użytkownika powinna zawierać od 4 do 150 znaków.</small>
            </div>
            <div class="form-group">
                {{ form.email.label_tag }}
                {{ form.email }}
            </div>
            <div class="form-group">
                {{ form.password1.label_tag }}
                {{ form.password1 }}
                <small class="text-muted">Hasło powinno zawierać co najmniej 8 znaków.</small>
            </div>
            <div class="form-group">
                {{ form.password2.label_tag }}
                {{ form.password2 }}
            </div>
            <button type="submit" class="btn btn-primary">Zarejestruj się</button>
        </form>
    </div>
{% endblock %}

myproject/blog/templates/blog/todo_confirm_delete.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <h1>Potwierdź usunięcie zadania</h1>
    <p>Czy na pewno chcesz usunąć to zadanie?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Tak, usuń</button>
        <a href="{% url 'trip' pk=trip_id %}">Anuluj</a>
    </form>
{% endblock %}

myproject/blog/templates/blog/todo_form.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <h1>Dodaj nowe zadanie</h1>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit">Dodaj zadanie</button>
    </form>
{% endblock %}

myproject/blog/templates/blog/trip_confirm_delete.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <h1>Kasuje wycieczkę: {{ object }}</h1>
    <br>
    <form method="POST" novalidate>
        {% csrf_token %}
        <div><input type="submit" value="Skasuj"></div>
    </form>
{% endblock %}

myproject/blog/templates/blog/trip_detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block page_title %} Widok dla {{ trip }} {% endblock %}

{% block content %}
    <div class="trip-details">
        <h1>Szczegóły wycieczki "{{ trip.title }}"</h1>
        <ul>
            <li><strong>Data startu:</strong>{{trip.start_date|date:"d.m.Y"}}</li>
            <li><strong>Data końca:</strong>{{trip.end_date|date:"d.m.Y"}}</li>
            <li><strong>Opis:</strong> {{trip.description}}</li>
            <li><strong>Kraje:</strong>{% for country in trip.countries.all %} {{ country.name }} {% endfor %}
            </li>
            <li><strong>Autor:</strong> {{ trip.author }}</li>
        </ul>
    </div>

{% if trip.author == request.user %}
<br>
  <div class="expenses">
        <h2>Wydatki</h2>
      <br>
        <table>
            <thead>
                <tr>
                    <th>Nazwa</th>
                    <th>Planowany koszt</th>
                    <th>Rzeczywisty koszt</th>
                    <th>Akcje</th>
                </tr>
            </thead>
            <tbody>
                {% for expense in expenses %}
                    <tr>
                        <td>{{ expense.name }}</td>
                        <td>{{ expense.planned_cost }}</td>
                        <td>{{ expense.actual_cost }}</td>
                        <td>
                            <a href="{% url 'expense_update' trip_id=trip.id expense_id=expense.id %}">Edytuj</a>
                            <a href="{% url 'expense_delete' trip_id=trip.id expense_id=expense.id %}">Usuń</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td><strong>Suma</strong></td>
                    <td><strong>{{ total_planned_cost }}</strong></td>
                    <td><strong>{{ total_actual_cost }}</strong></td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
      <a href="{% url 'expense_create' trip_id=trip.id %}" class="btn btn-primary"><strong>Dodaj wydatek</strong></a>
    </div>
 <div class="todos">
     <br>
            <h2>Lista rzeczy do zrobienia</h2>
     <br>
            <table>
                <thead>
                    <tr>
                        <th>Zadanie</th>
                        <th>Status</th>
                        <th>Akcje</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo in trip.to_dos.all %}
                        <tr>
                            <td>{{ todo.task }}</td>
                            <td>{{ todo.get_status_display }}</td>
                            <td>
                                <a href="{% url 'todo_update' trip_id=trip.id todo_id=todo.id %}">Edytuj</a>
                                <a href="{% url 'todo_delete' trip_id=trip.id todo_id=todo.id %}">Usuń</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
     <a href="{% url 'todo_create' trip_id=trip.id %}" class="btn btn-primary"><strong>Dodaj zadanie</strong></a>
        </div>

{% endif %}

{% endblock %}

myproject/blog/templates/blog/trip_form.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>Dodaj/edytuj wycieczkę</h1>
    <br>
    <form method="post" class="trip-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Tytuł:</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_start_date">Data rozpoczęcia:</label>
            {{ form.start_date }}
            <small class="text-muted">Data w formacie RRRR-MM-DD</small>

        </div>
        <div class="form-group">
            <label for="id_end_date">Data zakończenia:</label>
            {{ form.end_date }}
            <small class="text-muted">Data w formacie RRRR-MM-DD</small>

        </div>
        <div class="form-group">
            <label for="id_description">Opis:</label>
            {{ form.description }}
        </div>
        <div class="form-group" id="countries-checkbox">
            <label for="id_countries">Kraje:</label>
            <div>
                {% for country in form.countries.field.queryset %}
                    <p><input type="checkbox" name="countries" id="country_{{ forloop.counter }}" value="{{ country.id }}"> {{ country.name }}</p>
                {% endfor %}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Zapisz zmiany</button>
    </form>
</div>
{% endblock %}

myproject/blog/templates/blog/trips.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <h1>Moje wycieczki</h1>
    <br>
    {% for trip in trips %}
        <div>
            <p><a href="{% url 'trip' trip.id %}"><strong>{{ trip.title }}</strong></a></p>
            <p>Od {{ trip.start_date|date:"d.m.Y" }} do {{ trip.end_date|date:"d.m.Y" }}</p>
            <form action="{% url 'edit_trip' trip.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit">Edytuj</button>
            </form>
            <form action="{% url 'delete_trip' trip.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit">Usuń</button>
            </form>
        </div>
        <br>
    {% endfor %}
    <p><a href="{% url 'add_trip' %}"><strong>Dodaj nową wycieczkę</strong></a></p>
{% endblock %}